language: minimal
services:
- docker
env:
  global:
    secure: RbDeEwIZDMjdWG+o2T+p/YI24FXe9VGuRzrpvgMmh+tK7Gf+p2heVr7xyl0ekbgkrhqzai37IMHNxIP+TVit5FIeY4PilUM3i3JyPgIgF5U1kufYr5h7p7XazFWzAc58rY4rnAXO8XeUAwBaO1VPKrenquoHZ5hU3Jdzjfro1LFB/ONjRAR6Pw+1WLM26h7H/QEt7nvs/Q2Gr+XIKA2k73o9fjO87T0HvPVzZsS3R30gUlyvyOwoP5s8XPf40o0TC6G5C7SNkOsSyzOpGV13Lr/mEZ1vWkXnllsP2TZW9LsOwTsl8dRpb2GuoULC6KbqrV7t1g+ZreJ5webGIQzaaGIibwxGWZtBdrhZcqvAdyYmVHCeHRjowwJzxF6wRisEYa4b38etjWEdOAYSBirmEMVikb9qFD3pQos/YJmghLilBC0urrM7mHjBMLDt7t6Sk2qvp149KW1e6Ts3zpNTarVx0kxWXIs5vLu6NYQDb4BcXQnNbyFTxi658wbXA5ZQVIVz6SaE3ebGruZ0dQD13HYT9PzG/61kw+PT2sjzZQ6j1AkBHBSC8vNrU2boQvLs3OU0mKz6/dpqw6WGzFmCutyjtGh8vE7kRpYZXhLga3KPKApGvuU528JcwIw9TMEeMI+v3irkz4exsEnHRFbaEKzIfYdeyf1gsRmLDeZruBw=
  matrix:
  - PWNGUN_VERSION=2.23
  - PWNGUN_VERSION=2.27
  - PWNGUN_VERSION=2.30
  - PWNGUN_VERSION=2.31

before_install:
  - docker login -u fl3x3dd -p "$DOCKER_PASSWORD"

install:
  - ./build_nocache.sh

script:
  - ./publish.sh
