#!/bin/bash

set -e
docker ps > /dev/null

if [ -z $1 ]
then
    if [ "$(docker ps -a | grep pwngun)" ]
    then
        docker exec -it pwngun /bin/zsh
    else
        docker run -v /mnt/d/ctf:/ctf -w /ctf --env LANG=C.UTF-8 --env LC_ALL=C.UTF-8 --security-opt seccomp=unconfined --privileged --name pwngun -it --rm -h revker revker/pwngun:latest /bin/zsh
    fi
else
    if [ "$(docker ps -a | grep pwngun)" ]
    then
        docker exec -it pwngun /bin/zsh
    else
        docker run -v /mnt/d/ctf:/ctf -w /ctf --env LANG=C.UTF-8 --env LC_ALL=C.UTF-8 --security-opt seccomp=unconfined --privileged --name pwngun -it --rm -h revker revker/pwngun:$1 /bin/zsh
    fi
fi
